services:
  api:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5434/postgres
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5434"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
