services:
  api:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5434/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
